data = {
    'animations': ['custom_sparkle']
    ,'num_pixels': 400
    ,'brightness_high': 0.1
    ,'brightness_low': 0.025
    ,'animation_wait': 30
    ,'reset_lighting_timeout': 10
    ,'stop_time': '22:00'
    ,'sleep_time': 86400
    ,'ignore_sunset': 'True'
    ,'seconds_before_sunset': 900
    ,'custom_breathe_color': ['blue', 'purple', 'indigo']
    ,'custom_sparkle_color': 'pink'
    ,'custom_blink_color': 'jade'
    ,'multi_comet_color': 'palette_christmas'
    ,'custom_comet_color': 'None'
    ,'custom_chase_color': 'aqua'
    ,'multi_chase_color': 'palette_christmas'
    ,'cycle_color': 'palette_christmas'
    ,'custom_pacman_color': 'None'
    ,'custom_solid_color': 'white'
    ,'motion_solid_color': 'old_lace'
    , 'custom_sparkle_sparkles_override': 'None'
    , 'rainbow_sparkle_sparkles_override': 'None'
    , 'random_sparkle_sparkles_override': 'None'
    , 'custom_sparkle_speed_override': 'None'
    , 'rainbow_sparkle_speed_override': 'None'
    , 'random_sparkle_speed_override': 'None'
    , 'custom_breathe_speed_override': 'None'
    , 'random_breathe_speed_override': 'None'
    , 'random_chase_speed_override': 'None'
    , 'multi_chase_speed_override': 'None'
    , 'custom_chase_speed_override': 'None'
    , 'rainbow_chase_speed_override': 'None'
    , 'custom_blink_speed_override': 'None'
    , 'random_blink_speed_override': 'None'
    , 'cycle_speed_override': 'None'
    , 'rainbow_cycle_speed_override': 'None'
    , 'rainbow_comet_speed_override': 'None'
    , 'custom_comet_speed_override': 'None'
    , 'random_comet_speed_override': 'None'
    , 'multi_comet_speed_override': 'None'
    , 'custom_pacman_speed_override': 'None'
    , 'random_pacman_speed_override': 'None'
    , 'rainbow_speed_override': 'None'
    , 'rainbow_comet_tail_length_override': 'None'
    , 'custom_comet_tail_length_override': 'None'
    , 'random_comet_tail_length_override': 'None'
    , 'multi_comet_tail_length_override': 'None'
    , 'rainbow_comet_reverse_override': 'None'
    , 'multi_comet_reverse_override': 'None'
    , 'custom_comet_reverse_override': 'None'
    , 'random_comet_reverse_override': 'None'
    , 'rainbow_chase_reverse_override': 'None'
    , 'random_chase_reverse_override': 'None'
    , 'multi_chase_reverse_override': 'None'
    , 'custom_chase_reverse_override': 'None'
    , 'rainbow_chase_size_override': 'None'
    , 'multi_chase_size_override': 'None'
    , 'custom_chase_size_override': 'None'
    , 'random_chase_size_override': 'None'
    , 'rainbow_chase_spacing_override': 'None'
    , 'multi_chase_spacing_override': 'None'
    , 'custom_chase_spacing_override': 'None'
    , 'random_chase_spacing_override': 'None'
    , 'rainbow_chase_rate_override': 'None'
    , 'custom_chase_rate_override': 'None'
    , 'multi_chase_rate_override': 'None'
    , 'random_chase_rate_override': 'None'
    , 'random_breathe_step_override': 'None'
    , 'custom_breathe_step_override': 'None'
    , 'random_breathe_count_override': 'None'
    , 'custom_breathe_count_override': 'None'
}